apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: django-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      volumes:
      - name: ceph-pvc-storage
        persistentVolumeClaim:
          claimName: claim3
      containers:
      - name: django-ctr
        image: 11111111ukrnet/django_app:firsttry
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: ceph-pvc-storage
          mountPath: /opt/OpenWeatherMap/database
