---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  become: yes
  remote_user: vagrant
  vars:
    password: $6$tGl88xxU8$KGi.N4QeFfRvX9GtPwropmVFAMf3nd34AUpI8rm4m2tfytyXYErk.C9rlB4VveEfW/ImRKnh8lsnzdWzaXBzE1
  
  tasks:
    - name: Copy kubernetes list file  
      copy:
        src: files/kuber.list
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: 0644

    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Run the "apt-get update" 
      apt:
          update_cache: yes

    - name: Install required packages
      apt: 
          name: "{{ packages }}"
      vars:
          packages:
              - language-pack-ru  
              - ntp
              - ntpdate
              - docker.io
              - kubelet 
              - kubeadm 
              - kubernetes-cni 

    - name: Creater user ceph_admin
      user:
          name: ceph_admin
          groups: sudo


    - lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication no'
        line: 'PasswordAuthentication yes'
      notify:
          - restart ssh

    - name: Set authorized key took from file
      authorized_key:
          user: ceph_admin
          state: present
          key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"

    - name: Copy file ceph_admin for run commands wothout password 
      copy:
        src: files/ceph_admin.sudors
        dest: /etc/sudoers.d/ceph_admin
        mode: 0440

    - name: Creater user kube
      user:
          name: kube
          password: "{{password}}"

    - name: Copy  
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        owner: kube
        group: kube
        mode: 0644
      with_items:
          - { src: 'files/account.yaml', dst: '/home/kube/account.yaml' }
          - { src: 'files/ceph_storage.yaml', dst: '/home/kube/ceph_storage.yaml' }
          - { src: 'files/django_dp.yml', dst: '/home/kube/django_dp.yml' }
          - { src: 'files/storege_claim3.yml', dst: '/home/kube/storege_claim3.yml' }
          - { src: 'files/django_svc.yml', dst: '/home/kube/django_svc.yml' }
          - { src: 'files/Dockerfile', dst: '/home/kube/Dockerfile' }


    - name: Copy config file kuber  
      copy:
        src: files/create_docker.sh
        dest: /home/ceph_admin/create_docker.sh
        owner: ceph_admin
        group: ceph_admin 
        mode: 0755

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted 
